// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/DailyJobAlert.proto

package com.wanpng.emailalertapi.grpc.domain;

public final class DailyJobAlertProtos {
  private DailyJobAlertProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_domain_DailyJobAlert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_domain_DailyJobAlert_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!protos/domain/DailyJobAlert.proto\022\rpro" +
      "tos.domain\032!protos/domain/EmailAlertJob." +
      "proto\"y\n\rDailyJobAlert\022\r\n\005email\030\001 \001(\t\0226\n" +
      "\020email_alert_jobs\030\002 \003(\0132\034.protos.domain." +
      "EmailAlertJob\022\024\n\014header_title\030\003 \001(\t\022\013\n\003u" +
      "rl\030\004 \001(\tBm\n$com.wanpng.emailalertapi.grp" +
      "c.domainB\023DailyJobAlertProtosP\001Z.github." +
      "com/wanpng/email-alert-grpc/grpc/domainb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wanpng.emailalertapi.grpc.domain.EmailAlertJobProtos.getDescriptor(),
        });
    internal_static_protos_domain_DailyJobAlert_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_domain_DailyJobAlert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_domain_DailyJobAlert_descriptor,
        new java.lang.String[] { "Email", "EmailAlertJobs", "HeaderTitle", "Url", });
    com.wanpng.emailalertapi.grpc.domain.EmailAlertJobProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
