// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/DailyJobAlert.proto

package com.wanpng.emailalertapi.grpc.domain;

public interface DailyJobAlertOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.DailyJobAlert)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
   */
  java.util.List<com.wanpng.emailalertapi.grpc.domain.EmailAlertJob> 
      getEmailAlertJobsList();
  /**
   * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
   */
  com.wanpng.emailalertapi.grpc.domain.EmailAlertJob getEmailAlertJobs(int index);
  /**
   * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
   */
  int getEmailAlertJobsCount();
  /**
   * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
   */
  java.util.List<? extends com.wanpng.emailalertapi.grpc.domain.EmailAlertJobOrBuilder> 
      getEmailAlertJobsOrBuilderList();
  /**
   * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
   */
  com.wanpng.emailalertapi.grpc.domain.EmailAlertJobOrBuilder getEmailAlertJobsOrBuilder(
      int index);

  /**
   * <code>string header_title = 3;</code>
   * @return The headerTitle.
   */
  java.lang.String getHeaderTitle();
  /**
   * <code>string header_title = 3;</code>
   * @return The bytes for headerTitle.
   */
  com.google.protobuf.ByteString
      getHeaderTitleBytes();

  /**
   * <code>string url = 4;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 4;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>int32 count = 5;</code>
   * @return The count.
   */
  int getCount();

  /**
   * <code>string subject = 6;</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 6;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();
}
