// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/DailyJobAlert.proto

package com.wanpng.emailalertapi.grpc.domain;

/**
 * Protobuf type {@code protos.domain.DailyJobAlert}
 */
public final class DailyJobAlert extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.domain.DailyJobAlert)
    DailyJobAlertOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DailyJobAlert.newBuilder() to construct.
  private DailyJobAlert(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DailyJobAlert() {
    email_ = "";
    emailAlertJobs_ = java.util.Collections.emptyList();
    headerTitle_ = "";
    url_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DailyJobAlert();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DailyJobAlert(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              emailAlertJobs_ = new java.util.ArrayList<com.wanpng.emailalertapi.grpc.domain.EmailAlertJob>();
              mutable_bitField0_ |= 0x00000001;
            }
            emailAlertJobs_.add(
                input.readMessage(com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            headerTitle_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            url_ = s;
            break;
          }
          case 40: {

            count_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        emailAlertJobs_ = java.util.Collections.unmodifiableList(emailAlertJobs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.emailalertapi.grpc.domain.DailyJobAlertProtos.internal_static_protos_domain_DailyJobAlert_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.emailalertapi.grpc.domain.DailyJobAlertProtos.internal_static_protos_domain_DailyJobAlert_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.emailalertapi.grpc.domain.DailyJobAlert.class, com.wanpng.emailalertapi.grpc.domain.DailyJobAlert.Builder.class);
  }

  public static final int EMAIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_ALERT_JOBS_FIELD_NUMBER = 2;
  private java.util.List<com.wanpng.emailalertapi.grpc.domain.EmailAlertJob> emailAlertJobs_;
  /**
   * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.wanpng.emailalertapi.grpc.domain.EmailAlertJob> getEmailAlertJobsList() {
    return emailAlertJobs_;
  }
  /**
   * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.wanpng.emailalertapi.grpc.domain.EmailAlertJobOrBuilder> 
      getEmailAlertJobsOrBuilderList() {
    return emailAlertJobs_;
  }
  /**
   * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
   */
  @java.lang.Override
  public int getEmailAlertJobsCount() {
    return emailAlertJobs_.size();
  }
  /**
   * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
   */
  @java.lang.Override
  public com.wanpng.emailalertapi.grpc.domain.EmailAlertJob getEmailAlertJobs(int index) {
    return emailAlertJobs_.get(index);
  }
  /**
   * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
   */
  @java.lang.Override
  public com.wanpng.emailalertapi.grpc.domain.EmailAlertJobOrBuilder getEmailAlertJobsOrBuilder(
      int index) {
    return emailAlertJobs_.get(index);
  }

  public static final int HEADER_TITLE_FIELD_NUMBER = 3;
  private volatile java.lang.Object headerTitle_;
  /**
   * <code>string header_title = 3;</code>
   * @return The headerTitle.
   */
  @java.lang.Override
  public java.lang.String getHeaderTitle() {
    java.lang.Object ref = headerTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      headerTitle_ = s;
      return s;
    }
  }
  /**
   * <code>string header_title = 3;</code>
   * @return The bytes for headerTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHeaderTitleBytes() {
    java.lang.Object ref = headerTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      headerTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int URL_FIELD_NUMBER = 4;
  private volatile java.lang.Object url_;
  /**
   * <code>string url = 4;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <code>string url = 4;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNT_FIELD_NUMBER = 5;
  private int count_;
  /**
   * <code>int32 count = 5;</code>
   * @return The count.
   */
  @java.lang.Override
  public int getCount() {
    return count_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, email_);
    }
    for (int i = 0; i < emailAlertJobs_.size(); i++) {
      output.writeMessage(2, emailAlertJobs_.get(i));
    }
    if (!getHeaderTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, headerTitle_);
    }
    if (!getUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, url_);
    }
    if (count_ != 0) {
      output.writeInt32(5, count_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, email_);
    }
    for (int i = 0; i < emailAlertJobs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, emailAlertJobs_.get(i));
    }
    if (!getHeaderTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, headerTitle_);
    }
    if (!getUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, url_);
    }
    if (count_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, count_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.emailalertapi.grpc.domain.DailyJobAlert)) {
      return super.equals(obj);
    }
    com.wanpng.emailalertapi.grpc.domain.DailyJobAlert other = (com.wanpng.emailalertapi.grpc.domain.DailyJobAlert) obj;

    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getEmailAlertJobsList()
        .equals(other.getEmailAlertJobsList())) return false;
    if (!getHeaderTitle()
        .equals(other.getHeaderTitle())) return false;
    if (!getUrl()
        .equals(other.getUrl())) return false;
    if (getCount()
        != other.getCount()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    if (getEmailAlertJobsCount() > 0) {
      hash = (37 * hash) + EMAIL_ALERT_JOBS_FIELD_NUMBER;
      hash = (53 * hash) + getEmailAlertJobsList().hashCode();
    }
    hash = (37 * hash) + HEADER_TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getHeaderTitle().hashCode();
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.emailalertapi.grpc.domain.DailyJobAlert parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.emailalertapi.grpc.domain.DailyJobAlert parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.DailyJobAlert parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.emailalertapi.grpc.domain.DailyJobAlert parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.DailyJobAlert parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.emailalertapi.grpc.domain.DailyJobAlert parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.DailyJobAlert parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.emailalertapi.grpc.domain.DailyJobAlert parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.DailyJobAlert parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.emailalertapi.grpc.domain.DailyJobAlert parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.DailyJobAlert parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.emailalertapi.grpc.domain.DailyJobAlert parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.emailalertapi.grpc.domain.DailyJobAlert prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.domain.DailyJobAlert}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.domain.DailyJobAlert)
      com.wanpng.emailalertapi.grpc.domain.DailyJobAlertOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.emailalertapi.grpc.domain.DailyJobAlertProtos.internal_static_protos_domain_DailyJobAlert_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.emailalertapi.grpc.domain.DailyJobAlertProtos.internal_static_protos_domain_DailyJobAlert_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.emailalertapi.grpc.domain.DailyJobAlert.class, com.wanpng.emailalertapi.grpc.domain.DailyJobAlert.Builder.class);
    }

    // Construct using com.wanpng.emailalertapi.grpc.domain.DailyJobAlert.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEmailAlertJobsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      email_ = "";

      if (emailAlertJobsBuilder_ == null) {
        emailAlertJobs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        emailAlertJobsBuilder_.clear();
      }
      headerTitle_ = "";

      url_ = "";

      count_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.emailalertapi.grpc.domain.DailyJobAlertProtos.internal_static_protos_domain_DailyJobAlert_descriptor;
    }

    @java.lang.Override
    public com.wanpng.emailalertapi.grpc.domain.DailyJobAlert getDefaultInstanceForType() {
      return com.wanpng.emailalertapi.grpc.domain.DailyJobAlert.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.emailalertapi.grpc.domain.DailyJobAlert build() {
      com.wanpng.emailalertapi.grpc.domain.DailyJobAlert result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.emailalertapi.grpc.domain.DailyJobAlert buildPartial() {
      com.wanpng.emailalertapi.grpc.domain.DailyJobAlert result = new com.wanpng.emailalertapi.grpc.domain.DailyJobAlert(this);
      int from_bitField0_ = bitField0_;
      result.email_ = email_;
      if (emailAlertJobsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          emailAlertJobs_ = java.util.Collections.unmodifiableList(emailAlertJobs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.emailAlertJobs_ = emailAlertJobs_;
      } else {
        result.emailAlertJobs_ = emailAlertJobsBuilder_.build();
      }
      result.headerTitle_ = headerTitle_;
      result.url_ = url_;
      result.count_ = count_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.emailalertapi.grpc.domain.DailyJobAlert) {
        return mergeFrom((com.wanpng.emailalertapi.grpc.domain.DailyJobAlert)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.emailalertapi.grpc.domain.DailyJobAlert other) {
      if (other == com.wanpng.emailalertapi.grpc.domain.DailyJobAlert.getDefaultInstance()) return this;
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (emailAlertJobsBuilder_ == null) {
        if (!other.emailAlertJobs_.isEmpty()) {
          if (emailAlertJobs_.isEmpty()) {
            emailAlertJobs_ = other.emailAlertJobs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEmailAlertJobsIsMutable();
            emailAlertJobs_.addAll(other.emailAlertJobs_);
          }
          onChanged();
        }
      } else {
        if (!other.emailAlertJobs_.isEmpty()) {
          if (emailAlertJobsBuilder_.isEmpty()) {
            emailAlertJobsBuilder_.dispose();
            emailAlertJobsBuilder_ = null;
            emailAlertJobs_ = other.emailAlertJobs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            emailAlertJobsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEmailAlertJobsFieldBuilder() : null;
          } else {
            emailAlertJobsBuilder_.addAllMessages(other.emailAlertJobs_);
          }
        }
      }
      if (!other.getHeaderTitle().isEmpty()) {
        headerTitle_ = other.headerTitle_;
        onChanged();
      }
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        onChanged();
      }
      if (other.getCount() != 0) {
        setCount(other.getCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.emailalertapi.grpc.domain.DailyJobAlert parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.emailalertapi.grpc.domain.DailyJobAlert) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 1;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 1;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 1;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 1;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.wanpng.emailalertapi.grpc.domain.EmailAlertJob> emailAlertJobs_ =
      java.util.Collections.emptyList();
    private void ensureEmailAlertJobsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        emailAlertJobs_ = new java.util.ArrayList<com.wanpng.emailalertapi.grpc.domain.EmailAlertJob>(emailAlertJobs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.emailalertapi.grpc.domain.EmailAlertJob, com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.Builder, com.wanpng.emailalertapi.grpc.domain.EmailAlertJobOrBuilder> emailAlertJobsBuilder_;

    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public java.util.List<com.wanpng.emailalertapi.grpc.domain.EmailAlertJob> getEmailAlertJobsList() {
      if (emailAlertJobsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(emailAlertJobs_);
      } else {
        return emailAlertJobsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public int getEmailAlertJobsCount() {
      if (emailAlertJobsBuilder_ == null) {
        return emailAlertJobs_.size();
      } else {
        return emailAlertJobsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public com.wanpng.emailalertapi.grpc.domain.EmailAlertJob getEmailAlertJobs(int index) {
      if (emailAlertJobsBuilder_ == null) {
        return emailAlertJobs_.get(index);
      } else {
        return emailAlertJobsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public Builder setEmailAlertJobs(
        int index, com.wanpng.emailalertapi.grpc.domain.EmailAlertJob value) {
      if (emailAlertJobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmailAlertJobsIsMutable();
        emailAlertJobs_.set(index, value);
        onChanged();
      } else {
        emailAlertJobsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public Builder setEmailAlertJobs(
        int index, com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.Builder builderForValue) {
      if (emailAlertJobsBuilder_ == null) {
        ensureEmailAlertJobsIsMutable();
        emailAlertJobs_.set(index, builderForValue.build());
        onChanged();
      } else {
        emailAlertJobsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public Builder addEmailAlertJobs(com.wanpng.emailalertapi.grpc.domain.EmailAlertJob value) {
      if (emailAlertJobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmailAlertJobsIsMutable();
        emailAlertJobs_.add(value);
        onChanged();
      } else {
        emailAlertJobsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public Builder addEmailAlertJobs(
        int index, com.wanpng.emailalertapi.grpc.domain.EmailAlertJob value) {
      if (emailAlertJobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmailAlertJobsIsMutable();
        emailAlertJobs_.add(index, value);
        onChanged();
      } else {
        emailAlertJobsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public Builder addEmailAlertJobs(
        com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.Builder builderForValue) {
      if (emailAlertJobsBuilder_ == null) {
        ensureEmailAlertJobsIsMutable();
        emailAlertJobs_.add(builderForValue.build());
        onChanged();
      } else {
        emailAlertJobsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public Builder addEmailAlertJobs(
        int index, com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.Builder builderForValue) {
      if (emailAlertJobsBuilder_ == null) {
        ensureEmailAlertJobsIsMutable();
        emailAlertJobs_.add(index, builderForValue.build());
        onChanged();
      } else {
        emailAlertJobsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public Builder addAllEmailAlertJobs(
        java.lang.Iterable<? extends com.wanpng.emailalertapi.grpc.domain.EmailAlertJob> values) {
      if (emailAlertJobsBuilder_ == null) {
        ensureEmailAlertJobsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, emailAlertJobs_);
        onChanged();
      } else {
        emailAlertJobsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public Builder clearEmailAlertJobs() {
      if (emailAlertJobsBuilder_ == null) {
        emailAlertJobs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        emailAlertJobsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public Builder removeEmailAlertJobs(int index) {
      if (emailAlertJobsBuilder_ == null) {
        ensureEmailAlertJobsIsMutable();
        emailAlertJobs_.remove(index);
        onChanged();
      } else {
        emailAlertJobsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.Builder getEmailAlertJobsBuilder(
        int index) {
      return getEmailAlertJobsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public com.wanpng.emailalertapi.grpc.domain.EmailAlertJobOrBuilder getEmailAlertJobsOrBuilder(
        int index) {
      if (emailAlertJobsBuilder_ == null) {
        return emailAlertJobs_.get(index);  } else {
        return emailAlertJobsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public java.util.List<? extends com.wanpng.emailalertapi.grpc.domain.EmailAlertJobOrBuilder> 
         getEmailAlertJobsOrBuilderList() {
      if (emailAlertJobsBuilder_ != null) {
        return emailAlertJobsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(emailAlertJobs_);
      }
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.Builder addEmailAlertJobsBuilder() {
      return getEmailAlertJobsFieldBuilder().addBuilder(
          com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.Builder addEmailAlertJobsBuilder(
        int index) {
      return getEmailAlertJobsFieldBuilder().addBuilder(
          index, com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.EmailAlertJob email_alert_jobs = 2;</code>
     */
    public java.util.List<com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.Builder> 
         getEmailAlertJobsBuilderList() {
      return getEmailAlertJobsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.emailalertapi.grpc.domain.EmailAlertJob, com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.Builder, com.wanpng.emailalertapi.grpc.domain.EmailAlertJobOrBuilder> 
        getEmailAlertJobsFieldBuilder() {
      if (emailAlertJobsBuilder_ == null) {
        emailAlertJobsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.wanpng.emailalertapi.grpc.domain.EmailAlertJob, com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.Builder, com.wanpng.emailalertapi.grpc.domain.EmailAlertJobOrBuilder>(
                emailAlertJobs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        emailAlertJobs_ = null;
      }
      return emailAlertJobsBuilder_;
    }

    private java.lang.Object headerTitle_ = "";
    /**
     * <code>string header_title = 3;</code>
     * @return The headerTitle.
     */
    public java.lang.String getHeaderTitle() {
      java.lang.Object ref = headerTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headerTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string header_title = 3;</code>
     * @return The bytes for headerTitle.
     */
    public com.google.protobuf.ByteString
        getHeaderTitleBytes() {
      java.lang.Object ref = headerTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headerTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string header_title = 3;</code>
     * @param value The headerTitle to set.
     * @return This builder for chaining.
     */
    public Builder setHeaderTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      headerTitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string header_title = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeaderTitle() {
      
      headerTitle_ = getDefaultInstance().getHeaderTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string header_title = 3;</code>
     * @param value The bytes for headerTitle to set.
     * @return This builder for chaining.
     */
    public Builder setHeaderTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      headerTitle_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object url_ = "";
    /**
     * <code>string url = 4;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string url = 4;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string url = 4;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string url = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string url = 4;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value;
      onChanged();
      return this;
    }

    private int count_ ;
    /**
     * <code>int32 count = 5;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }
    /**
     * <code>int32 count = 5;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(int value) {
      
      count_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 count = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      
      count_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.domain.DailyJobAlert)
  }

  // @@protoc_insertion_point(class_scope:protos.domain.DailyJobAlert)
  private static final com.wanpng.emailalertapi.grpc.domain.DailyJobAlert DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.emailalertapi.grpc.domain.DailyJobAlert();
  }

  public static com.wanpng.emailalertapi.grpc.domain.DailyJobAlert getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DailyJobAlert>
      PARSER = new com.google.protobuf.AbstractParser<DailyJobAlert>() {
    @java.lang.Override
    public DailyJobAlert parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DailyJobAlert(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DailyJobAlert> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DailyJobAlert> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.emailalertapi.grpc.domain.DailyJobAlert getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

