// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/EmailAlertJob.proto

package com.wanpng.emailalertapi.grpc.domain;

public interface EmailAlertJobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.EmailAlertJob)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string job_title = 1;</code>
   * @return The jobTitle.
   */
  java.lang.String getJobTitle();
  /**
   * <code>string job_title = 1;</code>
   * @return The bytes for jobTitle.
   */
  com.google.protobuf.ByteString
      getJobTitleBytes();

  /**
   * <code>string company_name = 2;</code>
   * @return The companyName.
   */
  java.lang.String getCompanyName();
  /**
   * <code>string company_name = 2;</code>
   * @return The bytes for companyName.
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>string company_logo = 3;</code>
   * @return The companyLogo.
   */
  java.lang.String getCompanyLogo();
  /**
   * <code>string company_logo = 3;</code>
   * @return The bytes for companyLogo.
   */
  com.google.protobuf.ByteString
      getCompanyLogoBytes();

  /**
   * <code>bool is_lanco = 4;</code>
   * @return The isLanco.
   */
  boolean getIsLanco();

  /**
   * <code>string province = 5;</code>
   * @return The province.
   */
  java.lang.String getProvince();
  /**
   * <code>string province = 5;</code>
   * @return The bytes for province.
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <code>string career_level = 6;</code>
   * @return The careerLevel.
   */
  java.lang.String getCareerLevel();
  /**
   * <code>string career_level = 6;</code>
   * @return The bytes for careerLevel.
   */
  com.google.protobuf.ByteString
      getCareerLevelBytes();

  /**
   * <code>string employment_type = 7;</code>
   * @return The employmentType.
   */
  java.lang.String getEmploymentType();
  /**
   * <code>string employment_type = 7;</code>
   * @return The bytes for employmentType.
   */
  com.google.protobuf.ByteString
      getEmploymentTypeBytes();

  /**
   * <code>string url = 8;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 8;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string subject = 9;</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 9;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();
}
