// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/EmailAlertJob.proto

package com.wanpng.emailalertapi.grpc.domain;

/**
 * Protobuf type {@code protos.domain.EmailAlertJob}
 */
public final class EmailAlertJob extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.domain.EmailAlertJob)
    EmailAlertJobOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmailAlertJob.newBuilder() to construct.
  private EmailAlertJob(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmailAlertJob() {
    jobTitle_ = "";
    companyName_ = "";
    companyLogo_ = "";
    province_ = "";
    careerLevel_ = "";
    employmentType_ = "";
    url_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EmailAlertJob();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EmailAlertJob(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            jobTitle_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            companyName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            companyLogo_ = s;
            break;
          }
          case 32: {

            isLanco_ = input.readBool();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            province_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            careerLevel_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            employmentType_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            url_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.emailalertapi.grpc.domain.EmailAlertJobProtos.internal_static_protos_domain_EmailAlertJob_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.emailalertapi.grpc.domain.EmailAlertJobProtos.internal_static_protos_domain_EmailAlertJob_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.class, com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.Builder.class);
  }

  public static final int JOB_TITLE_FIELD_NUMBER = 1;
  private volatile java.lang.Object jobTitle_;
  /**
   * <code>string job_title = 1;</code>
   * @return The jobTitle.
   */
  @java.lang.Override
  public java.lang.String getJobTitle() {
    java.lang.Object ref = jobTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobTitle_ = s;
      return s;
    }
  }
  /**
   * <code>string job_title = 1;</code>
   * @return The bytes for jobTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJobTitleBytes() {
    java.lang.Object ref = jobTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANY_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object companyName_;
  /**
   * <code>string company_name = 2;</code>
   * @return The companyName.
   */
  @java.lang.Override
  public java.lang.String getCompanyName() {
    java.lang.Object ref = companyName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      companyName_ = s;
      return s;
    }
  }
  /**
   * <code>string company_name = 2;</code>
   * @return The bytes for companyName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCompanyNameBytes() {
    java.lang.Object ref = companyName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      companyName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANY_LOGO_FIELD_NUMBER = 3;
  private volatile java.lang.Object companyLogo_;
  /**
   * <code>string company_logo = 3;</code>
   * @return The companyLogo.
   */
  @java.lang.Override
  public java.lang.String getCompanyLogo() {
    java.lang.Object ref = companyLogo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      companyLogo_ = s;
      return s;
    }
  }
  /**
   * <code>string company_logo = 3;</code>
   * @return The bytes for companyLogo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCompanyLogoBytes() {
    java.lang.Object ref = companyLogo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      companyLogo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_LANCO_FIELD_NUMBER = 4;
  private boolean isLanco_;
  /**
   * <code>bool is_lanco = 4;</code>
   * @return The isLanco.
   */
  @java.lang.Override
  public boolean getIsLanco() {
    return isLanco_;
  }

  public static final int PROVINCE_FIELD_NUMBER = 5;
  private volatile java.lang.Object province_;
  /**
   * <code>string province = 5;</code>
   * @return The province.
   */
  @java.lang.Override
  public java.lang.String getProvince() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      province_ = s;
      return s;
    }
  }
  /**
   * <code>string province = 5;</code>
   * @return The bytes for province.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProvinceBytes() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      province_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAREER_LEVEL_FIELD_NUMBER = 6;
  private volatile java.lang.Object careerLevel_;
  /**
   * <code>string career_level = 6;</code>
   * @return The careerLevel.
   */
  @java.lang.Override
  public java.lang.String getCareerLevel() {
    java.lang.Object ref = careerLevel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      careerLevel_ = s;
      return s;
    }
  }
  /**
   * <code>string career_level = 6;</code>
   * @return The bytes for careerLevel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCareerLevelBytes() {
    java.lang.Object ref = careerLevel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      careerLevel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMPLOYMENT_TYPE_FIELD_NUMBER = 7;
  private volatile java.lang.Object employmentType_;
  /**
   * <code>string employment_type = 7;</code>
   * @return The employmentType.
   */
  @java.lang.Override
  public java.lang.String getEmploymentType() {
    java.lang.Object ref = employmentType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      employmentType_ = s;
      return s;
    }
  }
  /**
   * <code>string employment_type = 7;</code>
   * @return The bytes for employmentType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmploymentTypeBytes() {
    java.lang.Object ref = employmentType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      employmentType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int URL_FIELD_NUMBER = 8;
  private volatile java.lang.Object url_;
  /**
   * <code>string url = 8;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <code>string url = 8;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getJobTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jobTitle_);
    }
    if (!getCompanyNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, companyName_);
    }
    if (!getCompanyLogoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, companyLogo_);
    }
    if (isLanco_ != false) {
      output.writeBool(4, isLanco_);
    }
    if (!getProvinceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, province_);
    }
    if (!getCareerLevelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, careerLevel_);
    }
    if (!getEmploymentTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, employmentType_);
    }
    if (!getUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, url_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getJobTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jobTitle_);
    }
    if (!getCompanyNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, companyName_);
    }
    if (!getCompanyLogoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, companyLogo_);
    }
    if (isLanco_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isLanco_);
    }
    if (!getProvinceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, province_);
    }
    if (!getCareerLevelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, careerLevel_);
    }
    if (!getEmploymentTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, employmentType_);
    }
    if (!getUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, url_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.emailalertapi.grpc.domain.EmailAlertJob)) {
      return super.equals(obj);
    }
    com.wanpng.emailalertapi.grpc.domain.EmailAlertJob other = (com.wanpng.emailalertapi.grpc.domain.EmailAlertJob) obj;

    if (!getJobTitle()
        .equals(other.getJobTitle())) return false;
    if (!getCompanyName()
        .equals(other.getCompanyName())) return false;
    if (!getCompanyLogo()
        .equals(other.getCompanyLogo())) return false;
    if (getIsLanco()
        != other.getIsLanco()) return false;
    if (!getProvince()
        .equals(other.getProvince())) return false;
    if (!getCareerLevel()
        .equals(other.getCareerLevel())) return false;
    if (!getEmploymentType()
        .equals(other.getEmploymentType())) return false;
    if (!getUrl()
        .equals(other.getUrl())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JOB_TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getJobTitle().hashCode();
    hash = (37 * hash) + COMPANY_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCompanyName().hashCode();
    hash = (37 * hash) + COMPANY_LOGO_FIELD_NUMBER;
    hash = (53 * hash) + getCompanyLogo().hashCode();
    hash = (37 * hash) + IS_LANCO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsLanco());
    hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
    hash = (53 * hash) + getProvince().hashCode();
    hash = (37 * hash) + CAREER_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getCareerLevel().hashCode();
    hash = (37 * hash) + EMPLOYMENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEmploymentType().hashCode();
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.emailalertapi.grpc.domain.EmailAlertJob parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.emailalertapi.grpc.domain.EmailAlertJob parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.EmailAlertJob parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.emailalertapi.grpc.domain.EmailAlertJob parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.EmailAlertJob parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.emailalertapi.grpc.domain.EmailAlertJob parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.EmailAlertJob parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.emailalertapi.grpc.domain.EmailAlertJob parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.EmailAlertJob parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.emailalertapi.grpc.domain.EmailAlertJob parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.EmailAlertJob parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.emailalertapi.grpc.domain.EmailAlertJob parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.emailalertapi.grpc.domain.EmailAlertJob prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.domain.EmailAlertJob}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.domain.EmailAlertJob)
      com.wanpng.emailalertapi.grpc.domain.EmailAlertJobOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.emailalertapi.grpc.domain.EmailAlertJobProtos.internal_static_protos_domain_EmailAlertJob_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.emailalertapi.grpc.domain.EmailAlertJobProtos.internal_static_protos_domain_EmailAlertJob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.class, com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.Builder.class);
    }

    // Construct using com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      jobTitle_ = "";

      companyName_ = "";

      companyLogo_ = "";

      isLanco_ = false;

      province_ = "";

      careerLevel_ = "";

      employmentType_ = "";

      url_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.emailalertapi.grpc.domain.EmailAlertJobProtos.internal_static_protos_domain_EmailAlertJob_descriptor;
    }

    @java.lang.Override
    public com.wanpng.emailalertapi.grpc.domain.EmailAlertJob getDefaultInstanceForType() {
      return com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.emailalertapi.grpc.domain.EmailAlertJob build() {
      com.wanpng.emailalertapi.grpc.domain.EmailAlertJob result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.emailalertapi.grpc.domain.EmailAlertJob buildPartial() {
      com.wanpng.emailalertapi.grpc.domain.EmailAlertJob result = new com.wanpng.emailalertapi.grpc.domain.EmailAlertJob(this);
      result.jobTitle_ = jobTitle_;
      result.companyName_ = companyName_;
      result.companyLogo_ = companyLogo_;
      result.isLanco_ = isLanco_;
      result.province_ = province_;
      result.careerLevel_ = careerLevel_;
      result.employmentType_ = employmentType_;
      result.url_ = url_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.emailalertapi.grpc.domain.EmailAlertJob) {
        return mergeFrom((com.wanpng.emailalertapi.grpc.domain.EmailAlertJob)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.emailalertapi.grpc.domain.EmailAlertJob other) {
      if (other == com.wanpng.emailalertapi.grpc.domain.EmailAlertJob.getDefaultInstance()) return this;
      if (!other.getJobTitle().isEmpty()) {
        jobTitle_ = other.jobTitle_;
        onChanged();
      }
      if (!other.getCompanyName().isEmpty()) {
        companyName_ = other.companyName_;
        onChanged();
      }
      if (!other.getCompanyLogo().isEmpty()) {
        companyLogo_ = other.companyLogo_;
        onChanged();
      }
      if (other.getIsLanco() != false) {
        setIsLanco(other.getIsLanco());
      }
      if (!other.getProvince().isEmpty()) {
        province_ = other.province_;
        onChanged();
      }
      if (!other.getCareerLevel().isEmpty()) {
        careerLevel_ = other.careerLevel_;
        onChanged();
      }
      if (!other.getEmploymentType().isEmpty()) {
        employmentType_ = other.employmentType_;
        onChanged();
      }
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.emailalertapi.grpc.domain.EmailAlertJob parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.emailalertapi.grpc.domain.EmailAlertJob) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object jobTitle_ = "";
    /**
     * <code>string job_title = 1;</code>
     * @return The jobTitle.
     */
    public java.lang.String getJobTitle() {
      java.lang.Object ref = jobTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string job_title = 1;</code>
     * @return The bytes for jobTitle.
     */
    public com.google.protobuf.ByteString
        getJobTitleBytes() {
      java.lang.Object ref = jobTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string job_title = 1;</code>
     * @param value The jobTitle to set.
     * @return This builder for chaining.
     */
    public Builder setJobTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobTitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string job_title = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobTitle() {
      
      jobTitle_ = getDefaultInstance().getJobTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string job_title = 1;</code>
     * @param value The bytes for jobTitle to set.
     * @return This builder for chaining.
     */
    public Builder setJobTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobTitle_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object companyName_ = "";
    /**
     * <code>string company_name = 2;</code>
     * @return The companyName.
     */
    public java.lang.String getCompanyName() {
      java.lang.Object ref = companyName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string company_name = 2;</code>
     * @return The bytes for companyName.
     */
    public com.google.protobuf.ByteString
        getCompanyNameBytes() {
      java.lang.Object ref = companyName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string company_name = 2;</code>
     * @param value The companyName to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      companyName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string company_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompanyName() {
      
      companyName_ = getDefaultInstance().getCompanyName();
      onChanged();
      return this;
    }
    /**
     * <code>string company_name = 2;</code>
     * @param value The bytes for companyName to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      companyName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object companyLogo_ = "";
    /**
     * <code>string company_logo = 3;</code>
     * @return The companyLogo.
     */
    public java.lang.String getCompanyLogo() {
      java.lang.Object ref = companyLogo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyLogo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string company_logo = 3;</code>
     * @return The bytes for companyLogo.
     */
    public com.google.protobuf.ByteString
        getCompanyLogoBytes() {
      java.lang.Object ref = companyLogo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyLogo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string company_logo = 3;</code>
     * @param value The companyLogo to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyLogo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      companyLogo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string company_logo = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompanyLogo() {
      
      companyLogo_ = getDefaultInstance().getCompanyLogo();
      onChanged();
      return this;
    }
    /**
     * <code>string company_logo = 3;</code>
     * @param value The bytes for companyLogo to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyLogoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      companyLogo_ = value;
      onChanged();
      return this;
    }

    private boolean isLanco_ ;
    /**
     * <code>bool is_lanco = 4;</code>
     * @return The isLanco.
     */
    @java.lang.Override
    public boolean getIsLanco() {
      return isLanco_;
    }
    /**
     * <code>bool is_lanco = 4;</code>
     * @param value The isLanco to set.
     * @return This builder for chaining.
     */
    public Builder setIsLanco(boolean value) {
      
      isLanco_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_lanco = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsLanco() {
      
      isLanco_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object province_ = "";
    /**
     * <code>string province = 5;</code>
     * @return The province.
     */
    public java.lang.String getProvince() {
      java.lang.Object ref = province_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        province_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string province = 5;</code>
     * @return The bytes for province.
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      java.lang.Object ref = province_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string province = 5;</code>
     * @param value The province to set.
     * @return This builder for chaining.
     */
    public Builder setProvince(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      province_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string province = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearProvince() {
      
      province_ = getDefaultInstance().getProvince();
      onChanged();
      return this;
    }
    /**
     * <code>string province = 5;</code>
     * @param value The bytes for province to set.
     * @return This builder for chaining.
     */
    public Builder setProvinceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      province_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object careerLevel_ = "";
    /**
     * <code>string career_level = 6;</code>
     * @return The careerLevel.
     */
    public java.lang.String getCareerLevel() {
      java.lang.Object ref = careerLevel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        careerLevel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string career_level = 6;</code>
     * @return The bytes for careerLevel.
     */
    public com.google.protobuf.ByteString
        getCareerLevelBytes() {
      java.lang.Object ref = careerLevel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        careerLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string career_level = 6;</code>
     * @param value The careerLevel to set.
     * @return This builder for chaining.
     */
    public Builder setCareerLevel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      careerLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string career_level = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCareerLevel() {
      
      careerLevel_ = getDefaultInstance().getCareerLevel();
      onChanged();
      return this;
    }
    /**
     * <code>string career_level = 6;</code>
     * @param value The bytes for careerLevel to set.
     * @return This builder for chaining.
     */
    public Builder setCareerLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      careerLevel_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object employmentType_ = "";
    /**
     * <code>string employment_type = 7;</code>
     * @return The employmentType.
     */
    public java.lang.String getEmploymentType() {
      java.lang.Object ref = employmentType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        employmentType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string employment_type = 7;</code>
     * @return The bytes for employmentType.
     */
    public com.google.protobuf.ByteString
        getEmploymentTypeBytes() {
      java.lang.Object ref = employmentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employmentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string employment_type = 7;</code>
     * @param value The employmentType to set.
     * @return This builder for chaining.
     */
    public Builder setEmploymentType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      employmentType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string employment_type = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmploymentType() {
      
      employmentType_ = getDefaultInstance().getEmploymentType();
      onChanged();
      return this;
    }
    /**
     * <code>string employment_type = 7;</code>
     * @param value The bytes for employmentType to set.
     * @return This builder for chaining.
     */
    public Builder setEmploymentTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      employmentType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object url_ = "";
    /**
     * <code>string url = 8;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string url = 8;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string url = 8;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string url = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string url = 8;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.domain.EmailAlertJob)
  }

  // @@protoc_insertion_point(class_scope:protos.domain.EmailAlertJob)
  private static final com.wanpng.emailalertapi.grpc.domain.EmailAlertJob DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.emailalertapi.grpc.domain.EmailAlertJob();
  }

  public static com.wanpng.emailalertapi.grpc.domain.EmailAlertJob getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmailAlertJob>
      PARSER = new com.google.protobuf.AbstractParser<EmailAlertJob>() {
    @java.lang.Override
    public EmailAlertJob parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EmailAlertJob(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EmailAlertJob> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmailAlertJob> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.emailalertapi.grpc.domain.EmailAlertJob getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

