// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/JobInterviewRequest.proto

package com.wanpng.emailalertapi.grpc.domain;

/**
 * Protobuf type {@code protos.domain.JobInterviewRequest}
 */
public final class JobInterviewRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.domain.JobInterviewRequest)
    JobInterviewRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JobInterviewRequest.newBuilder() to construct.
  private JobInterviewRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobInterviewRequest() {
    employerId_ = "";
    employerFirstName_ = "";
    employerLastName_ = "";
    employerName_ = "";
    interviewStart_ = "";
    interviewEnd_ = "";
    jobId_ = "";
    jobTitle_ = "";
    province_ = "";
    careerLevel_ = "";
    employmentType_ = "";
    recipient_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JobInterviewRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JobInterviewRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            employerId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            employerFirstName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            employerLastName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            employerName_ = s;
            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (interviewDate_ != null) {
              subBuilder = interviewDate_.toBuilder();
            }
            interviewDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(interviewDate_);
              interviewDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            interviewStart_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            interviewEnd_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            jobId_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            jobTitle_ = s;
            break;
          }
          case 80: {

            isLanco_ = input.readBool();
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            province_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            careerLevel_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            employmentType_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            recipient_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.emailalertapi.grpc.domain.JobInterviewRequestProtos.internal_static_protos_domain_JobInterviewRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.emailalertapi.grpc.domain.JobInterviewRequestProtos.internal_static_protos_domain_JobInterviewRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest.class, com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest.Builder.class);
  }

  public static final int EMPLOYER_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object employerId_;
  /**
   * <code>string employer_id = 1;</code>
   * @return The employerId.
   */
  @java.lang.Override
  public java.lang.String getEmployerId() {
    java.lang.Object ref = employerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      employerId_ = s;
      return s;
    }
  }
  /**
   * <code>string employer_id = 1;</code>
   * @return The bytes for employerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmployerIdBytes() {
    java.lang.Object ref = employerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      employerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMPLOYER_FIRST_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object employerFirstName_;
  /**
   * <code>string employer_first_name = 2;</code>
   * @return The employerFirstName.
   */
  @java.lang.Override
  public java.lang.String getEmployerFirstName() {
    java.lang.Object ref = employerFirstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      employerFirstName_ = s;
      return s;
    }
  }
  /**
   * <code>string employer_first_name = 2;</code>
   * @return The bytes for employerFirstName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmployerFirstNameBytes() {
    java.lang.Object ref = employerFirstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      employerFirstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMPLOYER_LAST_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object employerLastName_;
  /**
   * <code>string employer_last_name = 3;</code>
   * @return The employerLastName.
   */
  @java.lang.Override
  public java.lang.String getEmployerLastName() {
    java.lang.Object ref = employerLastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      employerLastName_ = s;
      return s;
    }
  }
  /**
   * <code>string employer_last_name = 3;</code>
   * @return The bytes for employerLastName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmployerLastNameBytes() {
    java.lang.Object ref = employerLastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      employerLastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMPLOYER_NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object employerName_;
  /**
   * <code>string employer_name = 4;</code>
   * @return The employerName.
   */
  @java.lang.Override
  public java.lang.String getEmployerName() {
    java.lang.Object ref = employerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      employerName_ = s;
      return s;
    }
  }
  /**
   * <code>string employer_name = 4;</code>
   * @return The bytes for employerName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmployerNameBytes() {
    java.lang.Object ref = employerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      employerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTERVIEWDATE_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp interviewDate_;
  /**
   * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
   * @return Whether the interviewDate field is set.
   */
  @java.lang.Override
  public boolean hasInterviewDate() {
    return interviewDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
   * @return The interviewDate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getInterviewDate() {
    return interviewDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : interviewDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getInterviewDateOrBuilder() {
    return getInterviewDate();
  }

  public static final int INTERVIEWSTART_FIELD_NUMBER = 6;
  private volatile java.lang.Object interviewStart_;
  /**
   * <code>string interviewStart = 6;</code>
   * @return The interviewStart.
   */
  @java.lang.Override
  public java.lang.String getInterviewStart() {
    java.lang.Object ref = interviewStart_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      interviewStart_ = s;
      return s;
    }
  }
  /**
   * <code>string interviewStart = 6;</code>
   * @return The bytes for interviewStart.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInterviewStartBytes() {
    java.lang.Object ref = interviewStart_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      interviewStart_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTERVIEWEND_FIELD_NUMBER = 7;
  private volatile java.lang.Object interviewEnd_;
  /**
   * <code>string interviewEnd = 7;</code>
   * @return The interviewEnd.
   */
  @java.lang.Override
  public java.lang.String getInterviewEnd() {
    java.lang.Object ref = interviewEnd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      interviewEnd_ = s;
      return s;
    }
  }
  /**
   * <code>string interviewEnd = 7;</code>
   * @return The bytes for interviewEnd.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInterviewEndBytes() {
    java.lang.Object ref = interviewEnd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      interviewEnd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOB_ID_FIELD_NUMBER = 8;
  private volatile java.lang.Object jobId_;
  /**
   * <code>string job_id = 8;</code>
   * @return The jobId.
   */
  @java.lang.Override
  public java.lang.String getJobId() {
    java.lang.Object ref = jobId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobId_ = s;
      return s;
    }
  }
  /**
   * <code>string job_id = 8;</code>
   * @return The bytes for jobId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJobIdBytes() {
    java.lang.Object ref = jobId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOB_TITLE_FIELD_NUMBER = 9;
  private volatile java.lang.Object jobTitle_;
  /**
   * <code>string job_title = 9;</code>
   * @return The jobTitle.
   */
  @java.lang.Override
  public java.lang.String getJobTitle() {
    java.lang.Object ref = jobTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobTitle_ = s;
      return s;
    }
  }
  /**
   * <code>string job_title = 9;</code>
   * @return The bytes for jobTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJobTitleBytes() {
    java.lang.Object ref = jobTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_LANCO_FIELD_NUMBER = 10;
  private boolean isLanco_;
  /**
   * <code>bool is_lanco = 10;</code>
   * @return The isLanco.
   */
  @java.lang.Override
  public boolean getIsLanco() {
    return isLanco_;
  }

  public static final int PROVINCE_FIELD_NUMBER = 11;
  private volatile java.lang.Object province_;
  /**
   * <code>string province = 11;</code>
   * @return The province.
   */
  @java.lang.Override
  public java.lang.String getProvince() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      province_ = s;
      return s;
    }
  }
  /**
   * <code>string province = 11;</code>
   * @return The bytes for province.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProvinceBytes() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      province_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAREER_LEVEL_FIELD_NUMBER = 12;
  private volatile java.lang.Object careerLevel_;
  /**
   * <code>string career_level = 12;</code>
   * @return The careerLevel.
   */
  @java.lang.Override
  public java.lang.String getCareerLevel() {
    java.lang.Object ref = careerLevel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      careerLevel_ = s;
      return s;
    }
  }
  /**
   * <code>string career_level = 12;</code>
   * @return The bytes for careerLevel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCareerLevelBytes() {
    java.lang.Object ref = careerLevel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      careerLevel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMPLOYMENT_TYPE_FIELD_NUMBER = 13;
  private volatile java.lang.Object employmentType_;
  /**
   * <code>string employment_type = 13;</code>
   * @return The employmentType.
   */
  @java.lang.Override
  public java.lang.String getEmploymentType() {
    java.lang.Object ref = employmentType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      employmentType_ = s;
      return s;
    }
  }
  /**
   * <code>string employment_type = 13;</code>
   * @return The bytes for employmentType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmploymentTypeBytes() {
    java.lang.Object ref = employmentType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      employmentType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECIPIENT_FIELD_NUMBER = 14;
  private volatile java.lang.Object recipient_;
  /**
   * <code>string recipient = 14;</code>
   * @return The recipient.
   */
  @java.lang.Override
  public java.lang.String getRecipient() {
    java.lang.Object ref = recipient_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recipient_ = s;
      return s;
    }
  }
  /**
   * <code>string recipient = 14;</code>
   * @return The bytes for recipient.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecipientBytes() {
    java.lang.Object ref = recipient_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recipient_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEmployerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, employerId_);
    }
    if (!getEmployerFirstNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, employerFirstName_);
    }
    if (!getEmployerLastNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, employerLastName_);
    }
    if (!getEmployerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, employerName_);
    }
    if (interviewDate_ != null) {
      output.writeMessage(5, getInterviewDate());
    }
    if (!getInterviewStartBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, interviewStart_);
    }
    if (!getInterviewEndBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, interviewEnd_);
    }
    if (!getJobIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, jobId_);
    }
    if (!getJobTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, jobTitle_);
    }
    if (isLanco_ != false) {
      output.writeBool(10, isLanco_);
    }
    if (!getProvinceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, province_);
    }
    if (!getCareerLevelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, careerLevel_);
    }
    if (!getEmploymentTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, employmentType_);
    }
    if (!getRecipientBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, recipient_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEmployerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, employerId_);
    }
    if (!getEmployerFirstNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, employerFirstName_);
    }
    if (!getEmployerLastNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, employerLastName_);
    }
    if (!getEmployerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, employerName_);
    }
    if (interviewDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getInterviewDate());
    }
    if (!getInterviewStartBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, interviewStart_);
    }
    if (!getInterviewEndBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, interviewEnd_);
    }
    if (!getJobIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, jobId_);
    }
    if (!getJobTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, jobTitle_);
    }
    if (isLanco_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, isLanco_);
    }
    if (!getProvinceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, province_);
    }
    if (!getCareerLevelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, careerLevel_);
    }
    if (!getEmploymentTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, employmentType_);
    }
    if (!getRecipientBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, recipient_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest)) {
      return super.equals(obj);
    }
    com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest other = (com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest) obj;

    if (!getEmployerId()
        .equals(other.getEmployerId())) return false;
    if (!getEmployerFirstName()
        .equals(other.getEmployerFirstName())) return false;
    if (!getEmployerLastName()
        .equals(other.getEmployerLastName())) return false;
    if (!getEmployerName()
        .equals(other.getEmployerName())) return false;
    if (hasInterviewDate() != other.hasInterviewDate()) return false;
    if (hasInterviewDate()) {
      if (!getInterviewDate()
          .equals(other.getInterviewDate())) return false;
    }
    if (!getInterviewStart()
        .equals(other.getInterviewStart())) return false;
    if (!getInterviewEnd()
        .equals(other.getInterviewEnd())) return false;
    if (!getJobId()
        .equals(other.getJobId())) return false;
    if (!getJobTitle()
        .equals(other.getJobTitle())) return false;
    if (getIsLanco()
        != other.getIsLanco()) return false;
    if (!getProvince()
        .equals(other.getProvince())) return false;
    if (!getCareerLevel()
        .equals(other.getCareerLevel())) return false;
    if (!getEmploymentType()
        .equals(other.getEmploymentType())) return false;
    if (!getRecipient()
        .equals(other.getRecipient())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EMPLOYER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEmployerId().hashCode();
    hash = (37 * hash) + EMPLOYER_FIRST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getEmployerFirstName().hashCode();
    hash = (37 * hash) + EMPLOYER_LAST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getEmployerLastName().hashCode();
    hash = (37 * hash) + EMPLOYER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getEmployerName().hashCode();
    if (hasInterviewDate()) {
      hash = (37 * hash) + INTERVIEWDATE_FIELD_NUMBER;
      hash = (53 * hash) + getInterviewDate().hashCode();
    }
    hash = (37 * hash) + INTERVIEWSTART_FIELD_NUMBER;
    hash = (53 * hash) + getInterviewStart().hashCode();
    hash = (37 * hash) + INTERVIEWEND_FIELD_NUMBER;
    hash = (53 * hash) + getInterviewEnd().hashCode();
    hash = (37 * hash) + JOB_ID_FIELD_NUMBER;
    hash = (53 * hash) + getJobId().hashCode();
    hash = (37 * hash) + JOB_TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getJobTitle().hashCode();
    hash = (37 * hash) + IS_LANCO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsLanco());
    hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
    hash = (53 * hash) + getProvince().hashCode();
    hash = (37 * hash) + CAREER_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getCareerLevel().hashCode();
    hash = (37 * hash) + EMPLOYMENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEmploymentType().hashCode();
    hash = (37 * hash) + RECIPIENT_FIELD_NUMBER;
    hash = (53 * hash) + getRecipient().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.domain.JobInterviewRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.domain.JobInterviewRequest)
      com.wanpng.emailalertapi.grpc.domain.JobInterviewRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.emailalertapi.grpc.domain.JobInterviewRequestProtos.internal_static_protos_domain_JobInterviewRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.emailalertapi.grpc.domain.JobInterviewRequestProtos.internal_static_protos_domain_JobInterviewRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest.class, com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest.Builder.class);
    }

    // Construct using com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      employerId_ = "";

      employerFirstName_ = "";

      employerLastName_ = "";

      employerName_ = "";

      if (interviewDateBuilder_ == null) {
        interviewDate_ = null;
      } else {
        interviewDate_ = null;
        interviewDateBuilder_ = null;
      }
      interviewStart_ = "";

      interviewEnd_ = "";

      jobId_ = "";

      jobTitle_ = "";

      isLanco_ = false;

      province_ = "";

      careerLevel_ = "";

      employmentType_ = "";

      recipient_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.emailalertapi.grpc.domain.JobInterviewRequestProtos.internal_static_protos_domain_JobInterviewRequest_descriptor;
    }

    @java.lang.Override
    public com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest getDefaultInstanceForType() {
      return com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest build() {
      com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest buildPartial() {
      com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest result = new com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest(this);
      result.employerId_ = employerId_;
      result.employerFirstName_ = employerFirstName_;
      result.employerLastName_ = employerLastName_;
      result.employerName_ = employerName_;
      if (interviewDateBuilder_ == null) {
        result.interviewDate_ = interviewDate_;
      } else {
        result.interviewDate_ = interviewDateBuilder_.build();
      }
      result.interviewStart_ = interviewStart_;
      result.interviewEnd_ = interviewEnd_;
      result.jobId_ = jobId_;
      result.jobTitle_ = jobTitle_;
      result.isLanco_ = isLanco_;
      result.province_ = province_;
      result.careerLevel_ = careerLevel_;
      result.employmentType_ = employmentType_;
      result.recipient_ = recipient_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest) {
        return mergeFrom((com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest other) {
      if (other == com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest.getDefaultInstance()) return this;
      if (!other.getEmployerId().isEmpty()) {
        employerId_ = other.employerId_;
        onChanged();
      }
      if (!other.getEmployerFirstName().isEmpty()) {
        employerFirstName_ = other.employerFirstName_;
        onChanged();
      }
      if (!other.getEmployerLastName().isEmpty()) {
        employerLastName_ = other.employerLastName_;
        onChanged();
      }
      if (!other.getEmployerName().isEmpty()) {
        employerName_ = other.employerName_;
        onChanged();
      }
      if (other.hasInterviewDate()) {
        mergeInterviewDate(other.getInterviewDate());
      }
      if (!other.getInterviewStart().isEmpty()) {
        interviewStart_ = other.interviewStart_;
        onChanged();
      }
      if (!other.getInterviewEnd().isEmpty()) {
        interviewEnd_ = other.interviewEnd_;
        onChanged();
      }
      if (!other.getJobId().isEmpty()) {
        jobId_ = other.jobId_;
        onChanged();
      }
      if (!other.getJobTitle().isEmpty()) {
        jobTitle_ = other.jobTitle_;
        onChanged();
      }
      if (other.getIsLanco() != false) {
        setIsLanco(other.getIsLanco());
      }
      if (!other.getProvince().isEmpty()) {
        province_ = other.province_;
        onChanged();
      }
      if (!other.getCareerLevel().isEmpty()) {
        careerLevel_ = other.careerLevel_;
        onChanged();
      }
      if (!other.getEmploymentType().isEmpty()) {
        employmentType_ = other.employmentType_;
        onChanged();
      }
      if (!other.getRecipient().isEmpty()) {
        recipient_ = other.recipient_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object employerId_ = "";
    /**
     * <code>string employer_id = 1;</code>
     * @return The employerId.
     */
    public java.lang.String getEmployerId() {
      java.lang.Object ref = employerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        employerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string employer_id = 1;</code>
     * @return The bytes for employerId.
     */
    public com.google.protobuf.ByteString
        getEmployerIdBytes() {
      java.lang.Object ref = employerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string employer_id = 1;</code>
     * @param value The employerId to set.
     * @return This builder for chaining.
     */
    public Builder setEmployerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      employerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string employer_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmployerId() {
      
      employerId_ = getDefaultInstance().getEmployerId();
      onChanged();
      return this;
    }
    /**
     * <code>string employer_id = 1;</code>
     * @param value The bytes for employerId to set.
     * @return This builder for chaining.
     */
    public Builder setEmployerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      employerId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object employerFirstName_ = "";
    /**
     * <code>string employer_first_name = 2;</code>
     * @return The employerFirstName.
     */
    public java.lang.String getEmployerFirstName() {
      java.lang.Object ref = employerFirstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        employerFirstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string employer_first_name = 2;</code>
     * @return The bytes for employerFirstName.
     */
    public com.google.protobuf.ByteString
        getEmployerFirstNameBytes() {
      java.lang.Object ref = employerFirstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employerFirstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string employer_first_name = 2;</code>
     * @param value The employerFirstName to set.
     * @return This builder for chaining.
     */
    public Builder setEmployerFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      employerFirstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string employer_first_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmployerFirstName() {
      
      employerFirstName_ = getDefaultInstance().getEmployerFirstName();
      onChanged();
      return this;
    }
    /**
     * <code>string employer_first_name = 2;</code>
     * @param value The bytes for employerFirstName to set.
     * @return This builder for chaining.
     */
    public Builder setEmployerFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      employerFirstName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object employerLastName_ = "";
    /**
     * <code>string employer_last_name = 3;</code>
     * @return The employerLastName.
     */
    public java.lang.String getEmployerLastName() {
      java.lang.Object ref = employerLastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        employerLastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string employer_last_name = 3;</code>
     * @return The bytes for employerLastName.
     */
    public com.google.protobuf.ByteString
        getEmployerLastNameBytes() {
      java.lang.Object ref = employerLastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employerLastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string employer_last_name = 3;</code>
     * @param value The employerLastName to set.
     * @return This builder for chaining.
     */
    public Builder setEmployerLastName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      employerLastName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string employer_last_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmployerLastName() {
      
      employerLastName_ = getDefaultInstance().getEmployerLastName();
      onChanged();
      return this;
    }
    /**
     * <code>string employer_last_name = 3;</code>
     * @param value The bytes for employerLastName to set.
     * @return This builder for chaining.
     */
    public Builder setEmployerLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      employerLastName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object employerName_ = "";
    /**
     * <code>string employer_name = 4;</code>
     * @return The employerName.
     */
    public java.lang.String getEmployerName() {
      java.lang.Object ref = employerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        employerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string employer_name = 4;</code>
     * @return The bytes for employerName.
     */
    public com.google.protobuf.ByteString
        getEmployerNameBytes() {
      java.lang.Object ref = employerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string employer_name = 4;</code>
     * @param value The employerName to set.
     * @return This builder for chaining.
     */
    public Builder setEmployerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      employerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string employer_name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmployerName() {
      
      employerName_ = getDefaultInstance().getEmployerName();
      onChanged();
      return this;
    }
    /**
     * <code>string employer_name = 4;</code>
     * @param value The bytes for employerName to set.
     * @return This builder for chaining.
     */
    public Builder setEmployerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      employerName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp interviewDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> interviewDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
     * @return Whether the interviewDate field is set.
     */
    public boolean hasInterviewDate() {
      return interviewDateBuilder_ != null || interviewDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
     * @return The interviewDate.
     */
    public com.google.protobuf.Timestamp getInterviewDate() {
      if (interviewDateBuilder_ == null) {
        return interviewDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : interviewDate_;
      } else {
        return interviewDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
     */
    public Builder setInterviewDate(com.google.protobuf.Timestamp value) {
      if (interviewDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        interviewDate_ = value;
        onChanged();
      } else {
        interviewDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
     */
    public Builder setInterviewDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (interviewDateBuilder_ == null) {
        interviewDate_ = builderForValue.build();
        onChanged();
      } else {
        interviewDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
     */
    public Builder mergeInterviewDate(com.google.protobuf.Timestamp value) {
      if (interviewDateBuilder_ == null) {
        if (interviewDate_ != null) {
          interviewDate_ =
            com.google.protobuf.Timestamp.newBuilder(interviewDate_).mergeFrom(value).buildPartial();
        } else {
          interviewDate_ = value;
        }
        onChanged();
      } else {
        interviewDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
     */
    public Builder clearInterviewDate() {
      if (interviewDateBuilder_ == null) {
        interviewDate_ = null;
        onChanged();
      } else {
        interviewDate_ = null;
        interviewDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getInterviewDateBuilder() {
      
      onChanged();
      return getInterviewDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getInterviewDateOrBuilder() {
      if (interviewDateBuilder_ != null) {
        return interviewDateBuilder_.getMessageOrBuilder();
      } else {
        return interviewDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : interviewDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getInterviewDateFieldBuilder() {
      if (interviewDateBuilder_ == null) {
        interviewDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getInterviewDate(),
                getParentForChildren(),
                isClean());
        interviewDate_ = null;
      }
      return interviewDateBuilder_;
    }

    private java.lang.Object interviewStart_ = "";
    /**
     * <code>string interviewStart = 6;</code>
     * @return The interviewStart.
     */
    public java.lang.String getInterviewStart() {
      java.lang.Object ref = interviewStart_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interviewStart_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string interviewStart = 6;</code>
     * @return The bytes for interviewStart.
     */
    public com.google.protobuf.ByteString
        getInterviewStartBytes() {
      java.lang.Object ref = interviewStart_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interviewStart_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string interviewStart = 6;</code>
     * @param value The interviewStart to set.
     * @return This builder for chaining.
     */
    public Builder setInterviewStart(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      interviewStart_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string interviewStart = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterviewStart() {
      
      interviewStart_ = getDefaultInstance().getInterviewStart();
      onChanged();
      return this;
    }
    /**
     * <code>string interviewStart = 6;</code>
     * @param value The bytes for interviewStart to set.
     * @return This builder for chaining.
     */
    public Builder setInterviewStartBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      interviewStart_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object interviewEnd_ = "";
    /**
     * <code>string interviewEnd = 7;</code>
     * @return The interviewEnd.
     */
    public java.lang.String getInterviewEnd() {
      java.lang.Object ref = interviewEnd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interviewEnd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string interviewEnd = 7;</code>
     * @return The bytes for interviewEnd.
     */
    public com.google.protobuf.ByteString
        getInterviewEndBytes() {
      java.lang.Object ref = interviewEnd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interviewEnd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string interviewEnd = 7;</code>
     * @param value The interviewEnd to set.
     * @return This builder for chaining.
     */
    public Builder setInterviewEnd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      interviewEnd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string interviewEnd = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterviewEnd() {
      
      interviewEnd_ = getDefaultInstance().getInterviewEnd();
      onChanged();
      return this;
    }
    /**
     * <code>string interviewEnd = 7;</code>
     * @param value The bytes for interviewEnd to set.
     * @return This builder for chaining.
     */
    public Builder setInterviewEndBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      interviewEnd_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jobId_ = "";
    /**
     * <code>string job_id = 8;</code>
     * @return The jobId.
     */
    public java.lang.String getJobId() {
      java.lang.Object ref = jobId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string job_id = 8;</code>
     * @return The bytes for jobId.
     */
    public com.google.protobuf.ByteString
        getJobIdBytes() {
      java.lang.Object ref = jobId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string job_id = 8;</code>
     * @param value The jobId to set.
     * @return This builder for chaining.
     */
    public Builder setJobId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string job_id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobId() {
      
      jobId_ = getDefaultInstance().getJobId();
      onChanged();
      return this;
    }
    /**
     * <code>string job_id = 8;</code>
     * @param value The bytes for jobId to set.
     * @return This builder for chaining.
     */
    public Builder setJobIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jobTitle_ = "";
    /**
     * <code>string job_title = 9;</code>
     * @return The jobTitle.
     */
    public java.lang.String getJobTitle() {
      java.lang.Object ref = jobTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string job_title = 9;</code>
     * @return The bytes for jobTitle.
     */
    public com.google.protobuf.ByteString
        getJobTitleBytes() {
      java.lang.Object ref = jobTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string job_title = 9;</code>
     * @param value The jobTitle to set.
     * @return This builder for chaining.
     */
    public Builder setJobTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobTitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string job_title = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobTitle() {
      
      jobTitle_ = getDefaultInstance().getJobTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string job_title = 9;</code>
     * @param value The bytes for jobTitle to set.
     * @return This builder for chaining.
     */
    public Builder setJobTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobTitle_ = value;
      onChanged();
      return this;
    }

    private boolean isLanco_ ;
    /**
     * <code>bool is_lanco = 10;</code>
     * @return The isLanco.
     */
    @java.lang.Override
    public boolean getIsLanco() {
      return isLanco_;
    }
    /**
     * <code>bool is_lanco = 10;</code>
     * @param value The isLanco to set.
     * @return This builder for chaining.
     */
    public Builder setIsLanco(boolean value) {
      
      isLanco_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_lanco = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsLanco() {
      
      isLanco_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object province_ = "";
    /**
     * <code>string province = 11;</code>
     * @return The province.
     */
    public java.lang.String getProvince() {
      java.lang.Object ref = province_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        province_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string province = 11;</code>
     * @return The bytes for province.
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      java.lang.Object ref = province_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string province = 11;</code>
     * @param value The province to set.
     * @return This builder for chaining.
     */
    public Builder setProvince(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      province_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string province = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearProvince() {
      
      province_ = getDefaultInstance().getProvince();
      onChanged();
      return this;
    }
    /**
     * <code>string province = 11;</code>
     * @param value The bytes for province to set.
     * @return This builder for chaining.
     */
    public Builder setProvinceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      province_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object careerLevel_ = "";
    /**
     * <code>string career_level = 12;</code>
     * @return The careerLevel.
     */
    public java.lang.String getCareerLevel() {
      java.lang.Object ref = careerLevel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        careerLevel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string career_level = 12;</code>
     * @return The bytes for careerLevel.
     */
    public com.google.protobuf.ByteString
        getCareerLevelBytes() {
      java.lang.Object ref = careerLevel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        careerLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string career_level = 12;</code>
     * @param value The careerLevel to set.
     * @return This builder for chaining.
     */
    public Builder setCareerLevel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      careerLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string career_level = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearCareerLevel() {
      
      careerLevel_ = getDefaultInstance().getCareerLevel();
      onChanged();
      return this;
    }
    /**
     * <code>string career_level = 12;</code>
     * @param value The bytes for careerLevel to set.
     * @return This builder for chaining.
     */
    public Builder setCareerLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      careerLevel_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object employmentType_ = "";
    /**
     * <code>string employment_type = 13;</code>
     * @return The employmentType.
     */
    public java.lang.String getEmploymentType() {
      java.lang.Object ref = employmentType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        employmentType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string employment_type = 13;</code>
     * @return The bytes for employmentType.
     */
    public com.google.protobuf.ByteString
        getEmploymentTypeBytes() {
      java.lang.Object ref = employmentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employmentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string employment_type = 13;</code>
     * @param value The employmentType to set.
     * @return This builder for chaining.
     */
    public Builder setEmploymentType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      employmentType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string employment_type = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmploymentType() {
      
      employmentType_ = getDefaultInstance().getEmploymentType();
      onChanged();
      return this;
    }
    /**
     * <code>string employment_type = 13;</code>
     * @param value The bytes for employmentType to set.
     * @return This builder for chaining.
     */
    public Builder setEmploymentTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      employmentType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object recipient_ = "";
    /**
     * <code>string recipient = 14;</code>
     * @return The recipient.
     */
    public java.lang.String getRecipient() {
      java.lang.Object ref = recipient_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recipient_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string recipient = 14;</code>
     * @return The bytes for recipient.
     */
    public com.google.protobuf.ByteString
        getRecipientBytes() {
      java.lang.Object ref = recipient_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recipient_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string recipient = 14;</code>
     * @param value The recipient to set.
     * @return This builder for chaining.
     */
    public Builder setRecipient(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      recipient_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string recipient = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecipient() {
      
      recipient_ = getDefaultInstance().getRecipient();
      onChanged();
      return this;
    }
    /**
     * <code>string recipient = 14;</code>
     * @param value The bytes for recipient to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      recipient_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.domain.JobInterviewRequest)
  }

  // @@protoc_insertion_point(class_scope:protos.domain.JobInterviewRequest)
  private static final com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest();
  }

  public static com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobInterviewRequest>
      PARSER = new com.google.protobuf.AbstractParser<JobInterviewRequest>() {
    @java.lang.Override
    public JobInterviewRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JobInterviewRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JobInterviewRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobInterviewRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.emailalertapi.grpc.domain.JobInterviewRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

