// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/JobInterviewRequest.proto

package com.wanpng.emailalertapi.grpc.domain;

public interface JobInterviewRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.JobInterviewRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employer_id = 1;</code>
   * @return The employerId.
   */
  java.lang.String getEmployerId();
  /**
   * <code>string employer_id = 1;</code>
   * @return The bytes for employerId.
   */
  com.google.protobuf.ByteString
      getEmployerIdBytes();

  /**
   * <code>string employer_first_name = 2;</code>
   * @return The employerFirstName.
   */
  java.lang.String getEmployerFirstName();
  /**
   * <code>string employer_first_name = 2;</code>
   * @return The bytes for employerFirstName.
   */
  com.google.protobuf.ByteString
      getEmployerFirstNameBytes();

  /**
   * <code>string employer_last_name = 3;</code>
   * @return The employerLastName.
   */
  java.lang.String getEmployerLastName();
  /**
   * <code>string employer_last_name = 3;</code>
   * @return The bytes for employerLastName.
   */
  com.google.protobuf.ByteString
      getEmployerLastNameBytes();

  /**
   * <code>string employer_name = 4;</code>
   * @return The employerName.
   */
  java.lang.String getEmployerName();
  /**
   * <code>string employer_name = 4;</code>
   * @return The bytes for employerName.
   */
  com.google.protobuf.ByteString
      getEmployerNameBytes();

  /**
   * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
   * @return Whether the interviewDate field is set.
   */
  boolean hasInterviewDate();
  /**
   * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
   * @return The interviewDate.
   */
  com.google.protobuf.Timestamp getInterviewDate();
  /**
   * <code>.google.protobuf.Timestamp interviewDate = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getInterviewDateOrBuilder();

  /**
   * <code>string interviewStart = 6;</code>
   * @return The interviewStart.
   */
  java.lang.String getInterviewStart();
  /**
   * <code>string interviewStart = 6;</code>
   * @return The bytes for interviewStart.
   */
  com.google.protobuf.ByteString
      getInterviewStartBytes();

  /**
   * <code>string interviewEnd = 7;</code>
   * @return The interviewEnd.
   */
  java.lang.String getInterviewEnd();
  /**
   * <code>string interviewEnd = 7;</code>
   * @return The bytes for interviewEnd.
   */
  com.google.protobuf.ByteString
      getInterviewEndBytes();

  /**
   * <code>string job_id = 8;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 8;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <code>string job_title = 9;</code>
   * @return The jobTitle.
   */
  java.lang.String getJobTitle();
  /**
   * <code>string job_title = 9;</code>
   * @return The bytes for jobTitle.
   */
  com.google.protobuf.ByteString
      getJobTitleBytes();

  /**
   * <code>bool is_lanco = 10;</code>
   * @return The isLanco.
   */
  boolean getIsLanco();

  /**
   * <code>string province = 11;</code>
   * @return The province.
   */
  java.lang.String getProvince();
  /**
   * <code>string province = 11;</code>
   * @return The bytes for province.
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <code>string career_level = 12;</code>
   * @return The careerLevel.
   */
  java.lang.String getCareerLevel();
  /**
   * <code>string career_level = 12;</code>
   * @return The bytes for careerLevel.
   */
  com.google.protobuf.ByteString
      getCareerLevelBytes();

  /**
   * <code>string employment_type = 13;</code>
   * @return The employmentType.
   */
  java.lang.String getEmploymentType();
  /**
   * <code>string employment_type = 13;</code>
   * @return The bytes for employmentType.
   */
  com.google.protobuf.ByteString
      getEmploymentTypeBytes();

  /**
   * <code>string recipient = 14;</code>
   * @return The recipient.
   */
  java.lang.String getRecipient();
  /**
   * <code>string recipient = 14;</code>
   * @return The bytes for recipient.
   */
  com.google.protobuf.ByteString
      getRecipientBytes();
}
