// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/JobInvitation.proto

package com.wanpng.emailalertapi.grpc.domain;

public interface JobInvitationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.JobInvitation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employer_id = 1;</code>
   * @return The employerId.
   */
  java.lang.String getEmployerId();
  /**
   * <code>string employer_id = 1;</code>
   * @return The bytes for employerId.
   */
  com.google.protobuf.ByteString
      getEmployerIdBytes();

  /**
   * <code>string employer_first_name = 2;</code>
   * @return The employerFirstName.
   */
  java.lang.String getEmployerFirstName();
  /**
   * <code>string employer_first_name = 2;</code>
   * @return The bytes for employerFirstName.
   */
  com.google.protobuf.ByteString
      getEmployerFirstNameBytes();

  /**
   * <code>string employer_last_name = 3;</code>
   * @return The employerLastName.
   */
  java.lang.String getEmployerLastName();
  /**
   * <code>string employer_last_name = 3;</code>
   * @return The bytes for employerLastName.
   */
  com.google.protobuf.ByteString
      getEmployerLastNameBytes();

  /**
   * <code>string company_name = 4;</code>
   * @return The companyName.
   */
  java.lang.String getCompanyName();
  /**
   * <code>string company_name = 4;</code>
   * @return The bytes for companyName.
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>string logoPath = 5;</code>
   * @return The logoPath.
   */
  java.lang.String getLogoPath();
  /**
   * <code>string logoPath = 5;</code>
   * @return The bytes for logoPath.
   */
  com.google.protobuf.ByteString
      getLogoPathBytes();

  /**
   * <code>string job_id = 6;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 6;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <code>string job_title = 7;</code>
   * @return The jobTitle.
   */
  java.lang.String getJobTitle();
  /**
   * <code>string job_title = 7;</code>
   * @return The bytes for jobTitle.
   */
  com.google.protobuf.ByteString
      getJobTitleBytes();

  /**
   * <code>bool is_lanco = 8;</code>
   * @return The isLanco.
   */
  boolean getIsLanco();

  /**
   * <code>string province = 9;</code>
   * @return The province.
   */
  java.lang.String getProvince();
  /**
   * <code>string province = 9;</code>
   * @return The bytes for province.
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <code>string career_level = 10;</code>
   * @return The careerLevel.
   */
  java.lang.String getCareerLevel();
  /**
   * <code>string career_level = 10;</code>
   * @return The bytes for careerLevel.
   */
  com.google.protobuf.ByteString
      getCareerLevelBytes();

  /**
   * <code>string employment_type = 11;</code>
   * @return The employmentType.
   */
  java.lang.String getEmploymentType();
  /**
   * <code>string employment_type = 11;</code>
   * @return The bytes for employmentType.
   */
  com.google.protobuf.ByteString
      getEmploymentTypeBytes();

  /**
   * <code>string recipient = 12;</code>
   * @return The recipient.
   */
  java.lang.String getRecipient();
  /**
   * <code>string recipient = 12;</code>
   * @return The bytes for recipient.
   */
  com.google.protobuf.ByteString
      getRecipientBytes();
}
