// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/JobApplicationStatusUpdate.proto

package com.wanpng.emailalert.grpc.domain;

public interface JobApplicationStatusUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.JobApplicationStatusUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employer_id = 1;</code>
   * @return The employerId.
   */
  java.lang.String getEmployerId();
  /**
   * <code>string employer_id = 1;</code>
   * @return The bytes for employerId.
   */
  com.google.protobuf.ByteString
      getEmployerIdBytes();

  /**
   * <code>string employer_name = 2;</code>
   * @return The employerName.
   */
  java.lang.String getEmployerName();
  /**
   * <code>string employer_name = 2;</code>
   * @return The bytes for employerName.
   */
  com.google.protobuf.ByteString
      getEmployerNameBytes();

  /**
   * <code>string job_id = 3;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 3;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <code>string job_title = 4;</code>
   * @return The jobTitle.
   */
  java.lang.String getJobTitle();
  /**
   * <code>string job_title = 4;</code>
   * @return The bytes for jobTitle.
   */
  com.google.protobuf.ByteString
      getJobTitleBytes();

  /**
   * <code>string status = 5;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>bool is_lanco = 6;</code>
   * @return The isLanco.
   */
  boolean getIsLanco();

  /**
   * <code>string province = 7;</code>
   * @return The province.
   */
  java.lang.String getProvince();
  /**
   * <code>string province = 7;</code>
   * @return The bytes for province.
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <code>string career_level = 8;</code>
   * @return The careerLevel.
   */
  java.lang.String getCareerLevel();
  /**
   * <code>string career_level = 8;</code>
   * @return The bytes for careerLevel.
   */
  com.google.protobuf.ByteString
      getCareerLevelBytes();

  /**
   * <code>string employment_type = 9;</code>
   * @return The employmentType.
   */
  java.lang.String getEmploymentType();
  /**
   * <code>string employment_type = 9;</code>
   * @return The bytes for employmentType.
   */
  com.google.protobuf.ByteString
      getEmploymentTypeBytes();

  /**
   * <code>string recipient = 10;</code>
   * @return The recipient.
   */
  java.lang.String getRecipient();
  /**
   * <code>string recipient = 10;</code>
   * @return The bytes for recipient.
   */
  com.google.protobuf.ByteString
      getRecipientBytes();
}
