// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/job_email_alert_service.proto

package com.wanpng.emailalertapi.grpc.service;

public final class JobEmailAlertServiceProtos {
  private JobEmailAlertServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_JobEmailAlertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_JobEmailAlertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_SendJobApplicationStatusUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_SendJobApplicationStatusUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_SendDailyJobAlertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_SendDailyJobAlertRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,protos/service/job_email_alert_service" +
      ".proto\022\016protos.service\032!protos/domain/Jo" +
      "bInvitation.proto\032.protos/domain/JobAppl" +
      "icationStatusUpdate.proto\032\'protos/domain" +
      "/JobInterviewRequest.proto\032!protos/domai" +
      "n/DailyJobAlert.proto\":\n\025JobEmailAlertRe" +
      "sponse\022\021\n\tstatus_id\030\001 \001(\005\022\016\n\006status\030\002 \001(" +
      "\t\"w\n%SendJobApplicationStatusUpdateReque" +
      "st\022N\n\033jobApplicationStatusUpdates\030\001 \003(\0132" +
      ").protos.domain.JobApplicationStatusUpda" +
      "te\"R\n\030SendDailyJobAlertRequest\0226\n\020daily_" +
      "job_alerts\030\001 \003(\0132\034.protos.domain.DailyJo" +
      "bAlert2\274\003\n\024JobEmailAlertService\022X\n\021SendJ" +
      "obInvitation\022\034.protos.domain.JobInvitati" +
      "on\032%.protos.service.JobEmailAlertRespons" +
      "e\022~\n\036SendJobApplicationStatusUpdate\0225.pr" +
      "otos.service.SendJobApplicationStatusUpd" +
      "ateRequest\032%.protos.service.JobEmailAler" +
      "tResponse\022d\n\027SendJobInterviewRequest\022\".p" +
      "rotos.domain.JobInterviewRequest\032%.proto" +
      "s.service.JobEmailAlertResponse\022d\n\021SendD" +
      "ailyJobAlert\022(.protos.service.SendDailyJ" +
      "obAlertRequest\032%.protos.service.JobEmail" +
      "AlertResponseBv\n%com.wanpng.emailalertap" +
      "i.grpc.serviceB\032JobEmailAlertServiceProt" +
      "osP\001Z/github.com/wanpng/email-alert-grpc" +
      "/grpc/serviceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wanpng.emailalertapi.grpc.domain.JobInvitationProtos.getDescriptor(),
          com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdateProtos.getDescriptor(),
          com.wanpng.emailalertapi.grpc.domain.JobInterviewRequestProtos.getDescriptor(),
          com.wanpng.emailalertapi.grpc.domain.DailyJobAlertProtos.getDescriptor(),
        });
    internal_static_protos_service_JobEmailAlertResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_service_JobEmailAlertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_JobEmailAlertResponse_descriptor,
        new java.lang.String[] { "StatusId", "Status", });
    internal_static_protos_service_SendJobApplicationStatusUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_service_SendJobApplicationStatusUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_SendJobApplicationStatusUpdateRequest_descriptor,
        new java.lang.String[] { "JobApplicationStatusUpdates", });
    internal_static_protos_service_SendDailyJobAlertRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_service_SendDailyJobAlertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_SendDailyJobAlertRequest_descriptor,
        new java.lang.String[] { "DailyJobAlerts", });
    com.wanpng.emailalertapi.grpc.domain.JobInvitationProtos.getDescriptor();
    com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdateProtos.getDescriptor();
    com.wanpng.emailalertapi.grpc.domain.JobInterviewRequestProtos.getDescriptor();
    com.wanpng.emailalertapi.grpc.domain.DailyJobAlertProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
