// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/job_email_alert_service.proto

package com.wanpng.emailalertapi.grpc.service;

public final class JobEmailAlertServiceProtos {
  private JobEmailAlertServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_JobEmailAlertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_JobEmailAlertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_SendJobApplicationStatusUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_SendJobApplicationStatusUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_SendDailyJobAlertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_SendDailyJobAlertRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,protos/service/job_email_alert_service" +
      ".proto\022\016protos.service\032!protos/domain/Jo" +
      "bInvitation.proto\032.protos/domain/JobAppl" +
      "icationStatusUpdate.proto\032\'protos/domain" +
      "/JobInterviewRequest.proto\032!protos/domai" +
      "n/DailyJobAlert.proto\":\n\025JobEmailAlertRe" +
      "sponse\022\021\n\tstatus_id\030\001 \001(\005\022\016\n\006status\030\002 \001(" +
      "\t\"w\n%SendJobApplicationStatusUpdateReque" +
      "st\022N\n\033jobApplicationStatusUpdates\030\001 \003(\0132" +
      ").protos.domain.JobApplicationStatusUpda" +
      "te\"c\n\030SendDailyJobAlertRequest\022\017\n\007subjec" +
      "t\030\001 \001(\t\0226\n\020daily_job_alerts\030\002 \003(\0132\034.prot" +
      "os.domain.DailyJobAlert2\274\003\n\024JobEmailAler" +
      "tService\022X\n\021SendJobInvitation\022\034.protos.d" +
      "omain.JobInvitation\032%.protos.service.Job" +
      "EmailAlertResponse\022~\n\036SendJobApplication" +
      "StatusUpdate\0225.protos.service.SendJobApp" +
      "licationStatusUpdateRequest\032%.protos.ser" +
      "vice.JobEmailAlertResponse\022d\n\027SendJobInt" +
      "erviewRequest\022\".protos.domain.JobIntervi" +
      "ewRequest\032%.protos.service.JobEmailAlert" +
      "Response\022d\n\021SendDailyJobAlert\022(.protos.s" +
      "ervice.SendDailyJobAlertRequest\032%.protos" +
      ".service.JobEmailAlertResponseBv\n%com.wa" +
      "npng.emailalertapi.grpc.serviceB\032JobEmai" +
      "lAlertServiceProtosP\001Z/github.com/wanpng" +
      "/email-alert-grpc/grpc/serviceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wanpng.emailalertapi.grpc.domain.JobInvitationProtos.getDescriptor(),
          com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdateProtos.getDescriptor(),
          com.wanpng.emailalertapi.grpc.domain.JobInterviewRequestProtos.getDescriptor(),
          com.wanpng.emailalertapi.grpc.domain.DailyJobAlertProtos.getDescriptor(),
        });
    internal_static_protos_service_JobEmailAlertResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_service_JobEmailAlertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_JobEmailAlertResponse_descriptor,
        new java.lang.String[] { "StatusId", "Status", });
    internal_static_protos_service_SendJobApplicationStatusUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_service_SendJobApplicationStatusUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_SendJobApplicationStatusUpdateRequest_descriptor,
        new java.lang.String[] { "JobApplicationStatusUpdates", });
    internal_static_protos_service_SendDailyJobAlertRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_service_SendDailyJobAlertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_SendDailyJobAlertRequest_descriptor,
        new java.lang.String[] { "Subject", "DailyJobAlerts", });
    com.wanpng.emailalertapi.grpc.domain.JobInvitationProtos.getDescriptor();
    com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdateProtos.getDescriptor();
    com.wanpng.emailalertapi.grpc.domain.JobInterviewRequestProtos.getDescriptor();
    com.wanpng.emailalertapi.grpc.domain.DailyJobAlertProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
