// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/job_email_alert_service.proto

package com.wanpng.emailalertapi.grpc.service;

public interface JobEmailAlertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.JobEmailAlertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status_id = 1;</code>
   * @return The statusId.
   */
  int getStatusId();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
