// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/job_email_alert_service.proto

package com.wanpng.emailalertapi.grpc.service;

/**
 * Protobuf type {@code protos.service.SendJobApplicationStatusUpdateRequest}
 */
public final class SendJobApplicationStatusUpdateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.service.SendJobApplicationStatusUpdateRequest)
    SendJobApplicationStatusUpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SendJobApplicationStatusUpdateRequest.newBuilder() to construct.
  private SendJobApplicationStatusUpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SendJobApplicationStatusUpdateRequest() {
    jobApplicationStatusUpdates_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SendJobApplicationStatusUpdateRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SendJobApplicationStatusUpdateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              jobApplicationStatusUpdates_ = new java.util.ArrayList<com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate>();
              mutable_bitField0_ |= 0x00000001;
            }
            jobApplicationStatusUpdates_.add(
                input.readMessage(com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        jobApplicationStatusUpdates_ = java.util.Collections.unmodifiableList(jobApplicationStatusUpdates_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.emailalertapi.grpc.service.JobEmailAlertServiceProtos.internal_static_protos_service_SendJobApplicationStatusUpdateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.emailalertapi.grpc.service.JobEmailAlertServiceProtos.internal_static_protos_service_SendJobApplicationStatusUpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest.class, com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest.Builder.class);
  }

  public static final int JOBAPPLICATIONSTATUSUPDATES_FIELD_NUMBER = 1;
  private java.util.List<com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate> jobApplicationStatusUpdates_;
  /**
   * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate> getJobApplicationStatusUpdatesList() {
    return jobApplicationStatusUpdates_;
  }
  /**
   * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdateOrBuilder> 
      getJobApplicationStatusUpdatesOrBuilderList() {
    return jobApplicationStatusUpdates_;
  }
  /**
   * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
   */
  @java.lang.Override
  public int getJobApplicationStatusUpdatesCount() {
    return jobApplicationStatusUpdates_.size();
  }
  /**
   * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate getJobApplicationStatusUpdates(int index) {
    return jobApplicationStatusUpdates_.get(index);
  }
  /**
   * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdateOrBuilder getJobApplicationStatusUpdatesOrBuilder(
      int index) {
    return jobApplicationStatusUpdates_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jobApplicationStatusUpdates_.size(); i++) {
      output.writeMessage(1, jobApplicationStatusUpdates_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < jobApplicationStatusUpdates_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, jobApplicationStatusUpdates_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest)) {
      return super.equals(obj);
    }
    com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest other = (com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest) obj;

    if (!getJobApplicationStatusUpdatesList()
        .equals(other.getJobApplicationStatusUpdatesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getJobApplicationStatusUpdatesCount() > 0) {
      hash = (37 * hash) + JOBAPPLICATIONSTATUSUPDATES_FIELD_NUMBER;
      hash = (53 * hash) + getJobApplicationStatusUpdatesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.service.SendJobApplicationStatusUpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.service.SendJobApplicationStatusUpdateRequest)
      com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.emailalertapi.grpc.service.JobEmailAlertServiceProtos.internal_static_protos_service_SendJobApplicationStatusUpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.emailalertapi.grpc.service.JobEmailAlertServiceProtos.internal_static_protos_service_SendJobApplicationStatusUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest.class, com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest.Builder.class);
    }

    // Construct using com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getJobApplicationStatusUpdatesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        jobApplicationStatusUpdates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        jobApplicationStatusUpdatesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.emailalertapi.grpc.service.JobEmailAlertServiceProtos.internal_static_protos_service_SendJobApplicationStatusUpdateRequest_descriptor;
    }

    @java.lang.Override
    public com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest getDefaultInstanceForType() {
      return com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest build() {
      com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest buildPartial() {
      com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest result = new com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest(this);
      int from_bitField0_ = bitField0_;
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          jobApplicationStatusUpdates_ = java.util.Collections.unmodifiableList(jobApplicationStatusUpdates_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.jobApplicationStatusUpdates_ = jobApplicationStatusUpdates_;
      } else {
        result.jobApplicationStatusUpdates_ = jobApplicationStatusUpdatesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest) {
        return mergeFrom((com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest other) {
      if (other == com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest.getDefaultInstance()) return this;
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        if (!other.jobApplicationStatusUpdates_.isEmpty()) {
          if (jobApplicationStatusUpdates_.isEmpty()) {
            jobApplicationStatusUpdates_ = other.jobApplicationStatusUpdates_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJobApplicationStatusUpdatesIsMutable();
            jobApplicationStatusUpdates_.addAll(other.jobApplicationStatusUpdates_);
          }
          onChanged();
        }
      } else {
        if (!other.jobApplicationStatusUpdates_.isEmpty()) {
          if (jobApplicationStatusUpdatesBuilder_.isEmpty()) {
            jobApplicationStatusUpdatesBuilder_.dispose();
            jobApplicationStatusUpdatesBuilder_ = null;
            jobApplicationStatusUpdates_ = other.jobApplicationStatusUpdates_;
            bitField0_ = (bitField0_ & ~0x00000001);
            jobApplicationStatusUpdatesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJobApplicationStatusUpdatesFieldBuilder() : null;
          } else {
            jobApplicationStatusUpdatesBuilder_.addAllMessages(other.jobApplicationStatusUpdates_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate> jobApplicationStatusUpdates_ =
      java.util.Collections.emptyList();
    private void ensureJobApplicationStatusUpdatesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        jobApplicationStatusUpdates_ = new java.util.ArrayList<com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate>(jobApplicationStatusUpdates_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate, com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate.Builder, com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdateOrBuilder> jobApplicationStatusUpdatesBuilder_;

    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public java.util.List<com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate> getJobApplicationStatusUpdatesList() {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jobApplicationStatusUpdates_);
      } else {
        return jobApplicationStatusUpdatesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public int getJobApplicationStatusUpdatesCount() {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        return jobApplicationStatusUpdates_.size();
      } else {
        return jobApplicationStatusUpdatesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate getJobApplicationStatusUpdates(int index) {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        return jobApplicationStatusUpdates_.get(index);
      } else {
        return jobApplicationStatusUpdatesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public Builder setJobApplicationStatusUpdates(
        int index, com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate value) {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobApplicationStatusUpdatesIsMutable();
        jobApplicationStatusUpdates_.set(index, value);
        onChanged();
      } else {
        jobApplicationStatusUpdatesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public Builder setJobApplicationStatusUpdates(
        int index, com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate.Builder builderForValue) {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        ensureJobApplicationStatusUpdatesIsMutable();
        jobApplicationStatusUpdates_.set(index, builderForValue.build());
        onChanged();
      } else {
        jobApplicationStatusUpdatesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public Builder addJobApplicationStatusUpdates(com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate value) {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobApplicationStatusUpdatesIsMutable();
        jobApplicationStatusUpdates_.add(value);
        onChanged();
      } else {
        jobApplicationStatusUpdatesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public Builder addJobApplicationStatusUpdates(
        int index, com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate value) {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobApplicationStatusUpdatesIsMutable();
        jobApplicationStatusUpdates_.add(index, value);
        onChanged();
      } else {
        jobApplicationStatusUpdatesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public Builder addJobApplicationStatusUpdates(
        com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate.Builder builderForValue) {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        ensureJobApplicationStatusUpdatesIsMutable();
        jobApplicationStatusUpdates_.add(builderForValue.build());
        onChanged();
      } else {
        jobApplicationStatusUpdatesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public Builder addJobApplicationStatusUpdates(
        int index, com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate.Builder builderForValue) {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        ensureJobApplicationStatusUpdatesIsMutable();
        jobApplicationStatusUpdates_.add(index, builderForValue.build());
        onChanged();
      } else {
        jobApplicationStatusUpdatesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public Builder addAllJobApplicationStatusUpdates(
        java.lang.Iterable<? extends com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate> values) {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        ensureJobApplicationStatusUpdatesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jobApplicationStatusUpdates_);
        onChanged();
      } else {
        jobApplicationStatusUpdatesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public Builder clearJobApplicationStatusUpdates() {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        jobApplicationStatusUpdates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        jobApplicationStatusUpdatesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public Builder removeJobApplicationStatusUpdates(int index) {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        ensureJobApplicationStatusUpdatesIsMutable();
        jobApplicationStatusUpdates_.remove(index);
        onChanged();
      } else {
        jobApplicationStatusUpdatesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate.Builder getJobApplicationStatusUpdatesBuilder(
        int index) {
      return getJobApplicationStatusUpdatesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdateOrBuilder getJobApplicationStatusUpdatesOrBuilder(
        int index) {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        return jobApplicationStatusUpdates_.get(index);  } else {
        return jobApplicationStatusUpdatesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public java.util.List<? extends com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdateOrBuilder> 
         getJobApplicationStatusUpdatesOrBuilderList() {
      if (jobApplicationStatusUpdatesBuilder_ != null) {
        return jobApplicationStatusUpdatesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jobApplicationStatusUpdates_);
      }
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate.Builder addJobApplicationStatusUpdatesBuilder() {
      return getJobApplicationStatusUpdatesFieldBuilder().addBuilder(
          com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate.Builder addJobApplicationStatusUpdatesBuilder(
        int index) {
      return getJobApplicationStatusUpdatesFieldBuilder().addBuilder(
          index, com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.JobApplicationStatusUpdate jobApplicationStatusUpdates = 1;</code>
     */
    public java.util.List<com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate.Builder> 
         getJobApplicationStatusUpdatesBuilderList() {
      return getJobApplicationStatusUpdatesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate, com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate.Builder, com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdateOrBuilder> 
        getJobApplicationStatusUpdatesFieldBuilder() {
      if (jobApplicationStatusUpdatesBuilder_ == null) {
        jobApplicationStatusUpdatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate, com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdate.Builder, com.wanpng.emailalertapi.grpc.domain.JobApplicationStatusUpdateOrBuilder>(
                jobApplicationStatusUpdates_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        jobApplicationStatusUpdates_ = null;
      }
      return jobApplicationStatusUpdatesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.service.SendJobApplicationStatusUpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:protos.service.SendJobApplicationStatusUpdateRequest)
  private static final com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest();
  }

  public static com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendJobApplicationStatusUpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<SendJobApplicationStatusUpdateRequest>() {
    @java.lang.Override
    public SendJobApplicationStatusUpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SendJobApplicationStatusUpdateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SendJobApplicationStatusUpdateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendJobApplicationStatusUpdateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.emailalertapi.grpc.service.SendJobApplicationStatusUpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

